// site logo from: <a href="https://www.flaticon.com/free-icons/sun" title="sun icons">Sun icons created by Blackonion02 - Flaticon</a>
//Structure of navigation bar generated by Copilot
import { Link, NavLink, BrowserRouter as Router } from "react-router-dom";

//TODO: Add React routing to nav bar - when dealing with favourite locations
const Header = () => {
  return (
    <>
      <nav className="navbar navbar-expand-lg mt-0">
        <NavLink
        to='/'
        className="navbar-brand"
        >
 <img src="src/assets/siteLogo.png" alt=""></img>
        </NavLink>
        <button className="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <img src="src/assets/icons8-hamburger-menu.svg" alt="menu icon" />
        </button>
        <div className="collapse navbar-collapse" id="navbarNav">
          <ul className="navbar-nav ml-auto">
            <li className="nav-item active">
              <NavLink to='/' className="nav-link header-link">Home</NavLink>
              {/* <Link className="nav-link" to="/">Home</Link> */}
              {/* Below link generated by Copilot - in place until I figure out how to get the navbar links to work with React Router */}

              {/* <a className="nav-link" href={`${window.location.protocol}//${window.location.hostname}${window.location.port ? ':' + window.location.port : ''}`}>Home</a> */}
            </li>
            <li className="nav-item dropdown">
              <NavLink
                to='/favourites'
                className="nav-link dropdown-toggle"
                id="navbarDropdownMenuLink"
                role="button"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false"
              >My Saved Locations</NavLink>
              <div className="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <a className="dropdown-item" href="#">Action</a>
                <a className="dropdown-item" href="#">Another action</a>
                <a className="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
          </ul>
        </div>
      </nav>

    </>
  )
}

export default Header;